### ISSUE TITLE
ChromeDriver not found

### ISSUE THREAD

**Issue by dohnjoeph** [maximousblk/callow#10]
I am having an issue with ChromeDriver.

I installed it as well and added `import chromedriver_binary` as per https://pypi.org/project/chromedriver-binary/.

**Comment by maximousblk** [comment]
Hey @dohnjoeph 

You did not need to use `chromedriver_binary` package. only download the chromedriver binary from [chromedriver.chromium.org/downloads](https://chromedriver.chromium.org/downloads/) and put it in the installation directory or setup a path variable for it.

I'm sorry if the instructions were unclear.

Please post an update if this solution worked for you.

**Comment by dohnjoeph** [comment]
Initially, I downloaded the binary and it's on the same directory of callow. However, the issue is still the same.

I also setup a path variable.

**Comment by maximousblk** [comment]
Honestly, I cannot help without your environment information.

What OS are you running, What python version, what chrome version, etc.

I tested it and it is working fine. Try installing it again using the instructions [in this article](https://medium.com/@maximousblk/callow-6d42a14dbd50)

**Comment by maximousblk** [comment]
@dohnjoeph is it working now?

**Comment by maximousblk** [comment]
Closed due to inactivity.

This issue can be reopened if further discussion is required.
