### ISSUE TITLE
improvements & documentation

### ISSUE THREAD

**Issue by Fireflaker** [maximousblk/callow#28]
Username feild selector is invalid. 
    ->Username field selector is invalid.
-----
    Chromedriver is guaranteed won't work. 
    1. Goto https://sites.google.com/chromium.org/driver/downloads, download latest
    2. unzip and put exe into callow directory, replace existing chromedriver.exe
    3. if you're lucky it will work. otherwise, it will tell you which version to download.

**Comment by maximousblk** [comment]
I'm not sure what you are sayin...
