### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'

### ISSUE THREAD

**Issue by vvilm** [maximousblk/callow#33]
I have gotten to the last step of putting in the dictionary txt file, however after i do it opens the google chrome web page but then closes and gives me this error.

**Comment by maximousblk** [comment]
It looks like the `find_element_by_css_selector` method has been removed

https://stackoverflow.com/questions/72854116/selenium-attributeerror-webdriver-object-has-no-attribute-find-element-by-cs

will fix soon:tm:

**Comment by lunazx** [comment]
Hello when u fix it ?

**Comment by krookadile** [comment]
are you still working on this?

**Comment by krookadile** [comment]
it's working, it found the password on the sandbox site. is it normal for another google chrome tab to not open while searching for the correct password? because it found the password but it didn't log me in automatically or open another window

**Comment by maximousblk** [comment]
in the latest version i disabled the new window. this should have always been the case but chrome options were ignored by mistake
