### ISSUE TITLE
pls help when i start it all i get is this

### ISSUE THREAD

**Issue by hasan0610** [maximousblk/callow#36]
PS C:\Users\hasan\callow> python callow.py

     ____      _ _
    / ___|__ _| | | _____      __
   | |   / _` | | |/ _ \ \ /\ / /
   | |__| (_| | | | (_) \ V  V /
    \____\__,_|_|_|\___/ \_/\_/

[#] maximousblk/callow@v1.3

[~] Target login page (http/https only): https://askthemufti.us/
[#] Checking if site is accessible [OK]

[~] Username input selector: #login_email
[~] Password input selector: #login_pass
[~] Target username: admin
[~] Password dictionary: passlist.txt
Traceback (most recent call last):
  File "C:\Users\hasan\callow\callow.py", line 125, in <module>
    wizard()
  File "C:\Users\hasan\callow\callow.py", line 69, in wizard
    f = open(passlist, 'r') # Open password list
        ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'passlist.txt'
PS C:\Users\hasan\callow> python callow.py

     ____      _ _
    / ___|__ _| | | _____      __
   | |   / _` | | |/ _ \ \ /\ / /
   | |__| (_| | | | (_) \ V  V /
    \____\__,_|_|_|\___/ \_/\_/

[#] maximousblk/callow@v1.3

[~] Target login page (http/https only): https://askthemufti.us/
[#] Checking if site is accessible [OK]

[~] Username input selector: #login_email
[~] Password input selector: #login_pass
[~] Target username: admin
[~] Password dictionary: pass.txt

DevTools listening on ws://127.0.0.1:52349/devtools/browser/5add2d1b-7c8a-4127-b1f5-35a7c0be44ae

Target user: admin

Traceback (most recent call last):
  File "C:\Users\hasan\callow\callow.py", line 125, in <module>
    wizard()
  File "C:\Users\hasan\callow\callow.py", line 70, in wizard
    crack(username, usersel, passsel, passlist, website) # Start the attack
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hasan\callow\callow.py", line 109, in crack
    browser.find_element(By.CSS_SELECTOR, value=usersel).send_keys(username) # Enter username
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hasan\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webelement.py", line 233, in send_keys
    self._execute(
  File "C:\Users\hasan\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hasan\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hasan\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=109.0.5414.119)
Stacktrace:
Backtrace:
        (No symbol) [0x00DB6643]
        (No symbol) [0x00D4BE21]
        (No symbol) [0x00C4D960]
        (No symbol) [0x00C7C3BE]
        (No symbol) [0x00C7B7AB]
        (No symbol) [0x00C9FD7C]
        (No symbol) [0x00C7641F]
        (No symbol) [0x00CA00D4]
        (No symbol) [0x00CB6B09]
        (No symbol) [0x00C9FB76]
        (No symbol) [0x00C749C1]
        (No symbol) [0x00C75E5D]
        GetHandleVerifier [0x0102A142+2497106]
        GetHandleVerifier [0x010585D3+2686691]
        GetHandleVerifier [0x0105BB9C+2700460]
        GetHandleVerifier [0x00E63B10+635936]
        (No symbol) [0x00D54A1F]
        (No symbol) [0x00D5A418]
        (No symbol) [0x00D5A505]
        (No symbol) [0x00D6508B]
        BaseThreadInitThunk [0x75567D69+25]
        RtlInitializeExceptionChain [0x7764BB9B+107]
        RtlClearBits [0x7764BB1F+191]

**Comment by maximousblk** [comment]
callow will not work for the mentioned website because the login form does not exist until you click on the login link.
