### ISSUE TITLE
Extension for 2FA

### ISSUE THREAD

**Issue by steshi-chama** [maximousblk/callow#39]
Would it be possible to expand the capabilities to try to brute force a 2FA key?
I've locked myself out of an account because I'm stupid and would like to try to regain access.
My own attempts to set a fixed password and instead use the password_list parameter for the pop-up 2FA field have not yielded any results, unfortunately.

**Comment by maximousblk** [comment]
Usually 2FA codes are reset on failed attemts and after a time period so there is no way to outguess that. only possible solution is use the recovery options if setup or contact the service support resources and ask for a manual reset.
