### ISSUE TITLE
Cross platform compatibility

### ISSUE THREAD

**Issue by maximousblk** [maximousblk/callow#5]
This project currently only works on windows. Which is a limiting factor for many people who do not use windows.

**Comment by maximousblk** [comment]
To support multiple platforms, the included chromedriver binary needs to be removed. Which adds a bit of complexity to installing it. Releases will be fine, but the people using the git method will suffer and it is the primary distribution method.

**Comment by iMonZ** [comment]
> To support multiple platforms, the included chromedriver binary needs to be removed. Which adds a bit of complexity to installing it. Releases will be fine, but the people using the git method will suffer and it is the primary distribution method.

How about adding edgedriver support as well
